### ISSUE TITLE
open_tld_3d.launch

### ISSUE THREAD

**Issue by PuneetDheer** [MalcolmMielle/ros_open_tld_3d#2]
1) GUI is not opening even after launching the open_tld_3d.launch and open_tld_3d_double.launch.
2) open_tld.launch is not running.
Kindly rectify the issue and provide some implementation details.
Thank You.

**Comment by MalcolmMielle** [comment]
Can I get the error that are prompted when using the launch, if any, and your version of ROS. I made this program on ros indigo

**Comment by PuneetDheer** [comment]
ROSVERSION: INDIGO

1) open_tld_3d_double.launch (no error, but GUI is not opening.)
![opentld3ddouble](https://cloud.githubusercontent.com/assets/14956364/12782986/ca3f15bc-caa4-11e5-8a0a-71e6ef374617.png)

2) open_tld_3d.launch (no error, but GUI is not opening.)
![opentld3d](https://cloud.githubusercontent.com/assets/14956364/12783083/4d3848d0-caa5-11e5-94fb-65e64cea97b9.png)

3) open_tld.launch (the type you mentioned in the launch file is not existing in devel/lib/open_tld_3d after catkin_make)
![opentld](https://cloud.githubusercontent.com/assets/14956364/12783104/75b60464-caa5-11e5-8177-3e4b81d0f396.png)

**Comment by PuneetDheer** [comment]
Hello Malcolm

ROSVERSION: INDIGO
1) open_tld_3d_double.launch (no error, but GUI is not opening.)
2) open_tld_3d.launch (no error, but GUI is not opening.)

**Comment by PuneetDheer** [comment]
3) open_tld.launch (the type you mentioned in the launch file is not
existing in devel/lib/open_tld_3d after catkin_make)

Please help on this problem.

**Comment by MalcolmMielle** [comment]
I can't find the reason why you have no gui and it's a very old project I haven't maintained :/. You should try to check the global variable to make sure that the Graphical_interface is set to true. 

I can't even compile it on my machine anymore because it depend on an old version of openCV :S. I will maintain it if I have time but for now I can't.

**Comment by PuneetDheer** [comment]
I already changed the global variable in yaml file --> Graphical_interface=true.

I am using OpenCV2.4. 

Which version of opencv you used ?

**Comment by MalcolmMielle** [comment]
I'm using OpenCV 2.4.12 and I have this error while compiling the project

`make[2]: *** No rule to make target '/usr/lib64/libopencv_videostab.so.2.4.11', needed by '/home/malcolm/ros_catkin_ws/jade_ws/devel/lib/open_tld_3d/OpenTLD3D'.  Stop.
`

I probably hardcoded the Graphical_interface as false somewhere because my implementation is far from being the best :/

**Comment by PuneetDheer** [comment]
ok lets see :D

**Comment by PuneetDheer** [comment]
If you will find the solution of the GUI , plz let me know.

**Comment by PuneetDheer** [comment]
Hello Malcolm

Please check the repository and provide the solution for GUI which is not
opening.

**Comment by MalcolmMielle** [comment]
Do you have a Xtion or Kinect camera working and sending messages ? The gui won't stop if you don't have that since there is no image to display. You need to feed this topic  ' "camera/rgb/image" '

**Comment by PuneetDheer** [comment]
It is Necessary to use Xtion or Kinect camera ?
I am using ZED camera and already changed the topic according to ZED camera.

**Comment by MalcolmMielle** [comment]
You need to publish an image message into the topic "camera/rgb/image" and you should disable the 3d perception using ros parameter if you are using a 2d camera.

The only reason I can find is that no image is fed to the program. Have you tried reading the topic "camera/rgb/image" to make sure you're publishing something ? It's the reason the GUI doesn't start on mine since I have no camera and that's the only reason I can find :/.

**Comment by PuneetDheer** [comment]
I subscribed the image topic "camera/rgb/image_color" using ASUS XTION PRO. It's working fine. I faced a problem related to tracking in rviz which i solved after reading the code.

But when i was trying to do the same thing with "ZED 3D Camera" according to its own topic, then gui is not opening.

**Comment by MalcolmMielle** [comment]
So if I understand you correctly, the GUI started with an xtion but not with your other camera. 

This can only mean that the problem lies in the camera being published on the wrong topic. Opentld here reads on "camera/rgb/image" not "camera/rgb/image_color". Have you tried making sure that the topic are connected ? When you launch opentld and your camera, what does " rostopic info camera/rgb/image" gives you ?

**Comment by MalcolmMielle** [comment]
Closing the issue since no answer.
